
USE [BiblioAttendant]

--本テーブル
CREATE TABLE BOOK(
	ISBN_NO int NOT NULL,
	BOOK_NAME VARCHAR NOT NULL,
	AUTHOR VARCHAR,
	PUBLISHER VARCHAR,
	REGIST_DATETIME DATETIME NOT NULL,
	UPDATE_DATETIME DATETIME NOT NULL,
	DELETE_DATETIME DATETIME
)

--本詳細テーブル
CREATE TABLE BOOK_DETAIL(
	BOOK_ID int NOT NULL,
	ISBN_NO int NOT NULL,
	DETAIL VARCHAR,
	REGIST_DATETIME DATETIME NOT NULL,
	UPDATE_DATETIME DATETIME NOT NULL,
	DELETE_DATETIME DATETIME
)

--ユーザーテーブル
CREATE TABLE USER_INFO(
	USER_ID int NOT NULL IDENTITY (1, 1),
	USER_NAME VARCHAR NOT NULL,
	AUTHORITY int NOT NULL,
	REGIST_DATETIME DATETIME NOT NULL,
	DELETE_DATETIME DATETIME
)


--主キー設定
ALTER TABLE [BOOK]
	ADD PRIMARY KEY CLUSTERED ([ISBN_NO] ASC)
GO

ALTER TABLE [BOOK_DETAIL]
	ADD PRIMARY KEY CLUSTERED ([BOOK_ID] ASC,[ISBN_NO] ASC)
GO

ALTER TABLE [USER_INFO]
	ADD PRIMARY KEY CLUSTERED ([USER_ID] ASC)
GO

